[package]
name = "alona-page"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
camino = { version = "1.2.1", features = ["serde1"] }
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.5.48", features = ["derive"] }
fs-err = "2.11.0"
minijinja = "0.31.1"
pulldown-cmark = "0.9.6"
rss = { version = "2.0.12", features = ["validation", "atom"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.7.8"
tree-sitter = "0.20.10"
tree-sitter-c = "0.20.8"
tree-sitter-highlight = "0.20.1"
tree-sitter-rust = "0.20.4"
tree-sitter-toml = "0.20.0"
