base_url = "/~ne321/s2/"
base_domain = "www.doc.ic.ac.uk"

[[posts]]
title = "When the Simplest malloc(3) Implemenation is the Right Answer"
path = "posts/malloc.md"
date = "2023-12-09"
draft = true

[[posts]]
title = "A new site"
path = "posts/new-site.md"
date = "2022-04-05"
draft = true

[[posts]]
title = "Rustdoc JSON in 2022"
path = "posts/rustdoc-json-2022.md"
date = "2022-12-31"

[[posts]]
title = "Metaregex: Python can be fast too"
path = "posts/metaregex.md"
date = "2020-05-20"

[[redirects]]
from = "posts/2022/12/rustdoc-json-in-2022/"
to = "posts/rustdoc-json-2022/"

[[redirects]]
from = "posts/2020/05/metaregex-python-can-be-fast-too/"
to = "posts/metaregex/"
