base_url = "https://www.doc.ic.ac.uk/~ne321/"

[[posts]]
title = "A new site"
path = "posts/new-site.md"
date = "2022-04-05"
draft = true

[[posts]]
title = "Metaregex: Python can be fast too"
path = "posts/metaregex.md"
date = "2020-05-20"

[[posts]]
title = "Rustdoc JSON in 2022"
path = "posts/rustdoc-json-2022.md"
date = "2022-12-31"
