name: CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_INCREMENTAL: "0"
  CARGO_PROFILE_DEV_DEBUG: "0"
  CARGO_TERM_COLOR: "always"
  CARGO_TERM_PROGRESS_WHEN: "never"
  # Not serious code, I don't care
  # RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
    - run: cargo run -- --base-domain alona.page --base-url /
    - run: cp -r static/* out
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/trunk' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        user_name: "github-actions[bot]"
        user_email: "github-actions[bot]@users.noreply.github.com"
